# Site settings
github: [metadata]
title: AcklenAvenue-Website
email: info@acklenavenue.com
description: >
  Acklen Avenue is a team of agile software development professionals who are passionate about clean code and simple user experiences.
  Thanks to our team's heroic efforts and our clients' amazing ideas, Acklen Avenue lovingly delivers software daily from Nashville and around the world.

url: "http://acklenavenue.com"
twitter_username: acklenavenue
exclude: ['README.md']

# Build settings
environment: production
gems:
  - jekyll-gist
markdown: kramdown
permalink: /articles/:title
source: .
destination: ./_site
permalink: /:title

development:
  app_url: "http://localhost:4000/"


